RuteoPedidos.WebAdmin/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using RuteoPedidos.Core.DTO.Input;
using RuteoPedidos.Core.Model;
using RuteoPedidos.Core.Providers;
using RuteoPedidos.Core.Services;
using RuteoPedidos.WebAdmin.Extensions;
using RuteoPedidos.WebAdmin.Models;

namespace RuteoPedidos.WebAdmin.Controllers
{
    public class CuentaController : Controller
    {
        private readonly IUsuarioService _usuarioService;
        private readonly IMapper _mapper;
        private readonly ICifradoProvider _cifradoProvider;

        public CuentaController(IUsuarioService usuarioService,
            IMapper mapper, 
            ICifradoProvider cifradoProvider)
        {
            _usuarioService = usuarioService;
            _mapper = mapper;
            _cifradoProvider = cifradoProvider;
        }

        [HttpGet]
        public IActionResult CrearUsuario()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GuardarUsuario(CrearUsuarioVm crearUsuarioVm)
        {
            UsuarioInputDto usuarioInput = _mapper.Map<CrearUsuarioVm, UsuarioInputDto>(crearUsuarioVm);
            usuarioInput.Activo = true;
            usuarioInput.Password = _cifradoProvider.HashToMd5(crearUsuarioVm.PasswordText);

            await _usuarioService.CrearModificarUsuarioAsync(usuarioInput, true);
            return RedirectToAction("CrearUsuario");
        }


        [HttpPost]
        public async Task<IActionResult> CrearModificarUsuario(CrearUsuarioVm crearUsuarioVm)
        {
            UsuarioInputDto usuarioInput = _mapper.Map<CrearUsuarioVm, UsuarioInputDto>(crearUsuarioVm);
            usuarioInput.Activo = true;
            usuarioInput.Password = _cifradoProvider.HashToMd5(crearUsuarioVm.PasswordText);

            await _usuarioService.CrearModificarUsuarioAsync(usuarioInput, crearUsuarioVm.EsNuevo);
            return Json(new {exito = true});
        }

        [HttpGet]
        public IActionResult Login()
        {
            ObjetoModelStateView<LoginVm> objetoModelStateView = TempData.Get<ObjetoModelStateView<LoginVm>>("modelLogin");

            //Logica para leer el model state
            if (objetoModelStateView != null)
            {
                foreach (KeyValuePair<string, string> keyValuePair in objetoModelStateView.ElementosError)
                {
                    ModelState.AddModelError(keyValuePair.Key, keyValuePair.Value);
                }
            }

            return View(objetoModelStateView?.Modelo);
        }

        [HttpPost]
        public async Task<IActionResult> Ingresar(LoginVm loginVm)
        {
            //Primero validamos que la data vaya bien
            if (ModelState.IsValid == false)
            {
                ObjetoModelStateView<LoginVm> objetoModelStateView = new ObjetoModelStateView<LoginVm>()
                {
                    ElementosError = ModelState.Where(y => y.Value.Errors.Any()).Select(x =>
                        new KeyValuePair<string, string>(x.Key, x.Value.Errors.First().ErrorMessage)).ToList(),
                    Modelo = loginVm
                };
                TempData.Put("modelLogin", objetoModelStateView);
                return RedirectToAction("Login");
            }

            bool loginValido = await _usuarioService.ValidarLoginAsync(loginVm.Usuario, loginVm.Password);

            if (loginValido == false)
            {
                ModelState.AddModelError(string.Empty, "Los datos de ingreso no son válidos");
                ObjetoModelStateView<LoginVm> objetoModelStateView = new ObjetoModelStateView<LoginVm>()
                {
                    ElementosError = ModelState.Where(y => y.Value.Errors.Any()).Select(x =>
                        new KeyValuePair<string, string>(x.Key, x.Value.Errors.First().ErrorMessage)).ToList(),
                    Modelo = loginVm
                };
                TempData.Put("modelLogin", objetoModelStateView);
                return RedirectToAction("Login");
            }

            //Como es login valido, mando a sacar el usuario para tener datos
            Usuario usuario = await _usuarioService.GetUsuarioAsync(loginVm.Usuario);

            //En este punto el login es valido y lo mandamos al home
            ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, loginVm.Usuario));
            identity.AddClaim(new Claim(ClaimTypes.Name, loginVm.Usuario));
            identity.AddClaim(new Claim(ClaimTypes.Email, usuario.Email));
            //Agregamos claims nuestros
            identity.AddClaim(new Claim("nombreCompleto", usuario.ImprimirNombreCompleto()));
            identity.AddClaim(new Claim("idCuenta", usuario.IdCuenta.ToString()));

            ClaimsPrincipal principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties { IsPersistent = true });

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync("Cookies");
            return RedirectToAction("Login");
        }
    }
}

RuteoPedidos.WebAdmin/Views/Cuenta/CrearUsuario.cshtml
@model RuteoPedidos.WebAdmin.Models.CrearUsuarioVm
@{
    ViewData["Title"] = "Crear Usuario";
}

<h1>CrearUsuario</h1>

<form asp-controller="Cuenta" asp-action="GuardarUsuario" method="post">
    <label asp-for="IdUsuario">Usuario: </label>
    <input asp-for="IdUsuario" />
    <br />
    <label asp-for="Nombre">Nombre: </label>
    <input asp-for="Nombre" />
    <br />
    <label asp-for="Apellido">Apellido: </label>
    <input asp-for="Apellido" />
    <br />
    <label asp-for="PasswordText">Password: </label>
    <input asp-for="PasswordText" />
    <br />
    <label asp-for="Email">Email: </label>
    <input asp-for="Email" />
    <br />
    <label asp-for="IdCuenta">Codigo Cuenta: </label>
    <input asp-for="IdCuenta" />
    <br />
    <label asp-for="IdMotorista">Codigo Motorista (opcional): </label>
    <input asp-for="IdMotorista" />
    <br />

    <button type="submit">Guardar</button>

</form>

RuteoPedidos.WebAdmin/Views/Cuenta/Login.cshtml
@model LoginVm
@{
    ViewBag.Title = "Login";
    Layout = "_LayoutLogin";
}

<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">
        <form class="form" method="post" asp-controller="Cuenta" asp-action="Ingresar" id="formLogin">
            
            <div class="card card-login card-hidden">
                <div class="card-header card-header-rose text-center">
                    <h4 class="card-title">Login</h4>
                </div>
                <div class="card-body ">
                    <p class="card-description text-center">Ingrese sus credenciales</p>
                    <span class="bmd-form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="material-icons">email</i>
                                </span>
                            </div>
                            <input asp-for="Usuario" class="form-control" placeholder="Email...">
                        </div>
                    </span>
                    <span class="bmd-form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="material-icons">lock_outline</i>
                                </span>
                            </div>
                            <input asp-for="Password" type="password" class="form-control" placeholder="Password...">
                        </div>
                    </span>
                </div>
                <br/>
                
                <div class="card-footer justify-content-center">
                    <button type="submit" class="btn btn-rose btn-link btn-lg">Ingresar</button>
                </div>

            </div>
            <div class="alert alert" id="panelErrores" style="display: none">
                
                <span>
                    <div id="divValidadores" asp-validation-summary="All"></div>
                </span>
            </div>
        </form>
        
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function() {
            $('#formLogin').each(function() {
                var validator = $(this).data('validator');
                if (validator) {
                    validator.settings.showErrors = function(map, errors) {
                        this.defaultShowErrors();
                        if ($('div[data-valmsg-summary=true] li:visible').length) {
                            this.checkForm();
                            if (this.errorList.length) {
                                $(this.currentForm).triggerHandler("invalid-form", [this]);
                                $("#panelErrores").show();
                            }
                            else
                            {
                                $(this.currentForm).resetSummary();
                                $("#panelErrores").hide();
                            }

                        }
                    };
                }
            });

            //Veo si hay errores para ver si debo ocultar el panel
            if ($("#divValidadores").attr('class') === "validation-summary-errors") {
                $("#panelErrores").show();
            }

            $("#formLogin").submit(function(e) {
                var self = this;
                if ($(self).valid() == false) {
                    e.preventDefault();
                    $("#panelErrores").show();
                }
            });
        });

        jQuery.fn.resetSummary = function () {
            var form = this.is('form') ? this : this.closest('form');
            form.find("[data-valmsg-summary=true]")
                .removeClass("validation-summary-errors")
                .addClass("validation-summary-valid")
                .find("ul")
                .empty();
            return this;
        }
    </script>
}