RuteoPedidos.WebAdmin/Controllers/TareasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using RuteoPedidos.Core.DTO.Input.Tareas;
using RuteoPedidos.Core.Model;
using RuteoPedidos.Core.Model.Tareas;
using RuteoPedidos.Core.Services;
using RuteoPedidos.WebAdmin.Models;

namespace RuteoPedidos.WebAdmin.Controllers
{
    [Authorize(AuthenticationSchemes = "Cookies")]
    public class TareasController: Controller
    {
        private readonly IMapper _mapper;
        private readonly ITareasService _tareasService;
        private readonly IUsuarioService _usuarioService;

        public TareasController(
            ITareasService tareasService, 
            IMapper mapper,
            IUsuarioService usuarioService)
        {
            _tareasService = tareasService;
            _mapper = mapper;
            _usuarioService = usuarioService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {

            int idCuenta = await GetIdCuentaAsync();
            //Listar las tareas
            EntidadPaginada<Tarea> tareas = await _tareasService.GetTareasAsync(new int[] { }, idCuenta,
                DateTimeOffset.Now.AddYears(-7), null, 1,
                int.MaxValue);

            return View(tareas.Resultados);
        }

        [HttpPost]
        public async Task<IActionResult> GuardarTarea(CrearTareaVm crearTareaVm)
        {
            TareaInputDto tareaInput = _mapper.Map<CrearTareaVm, TareaInputDto>(crearTareaVm);

            await _tareasService.CrearTareaAsync(tareaInput, crearTareaVm.GenerarCliente);

            return new JsonResult(new {exito = true});
        }

        private async Task<int> GetIdCuentaAsync()
        {
            int idCuenta;

            //Saco la cuenta claim del user
            string cuentaClaim = User.Claims.FirstOrDefault(x => x.Type == "idCuenta")?.Value;

            //Si no hay claims, saco la cuenta de la base
            if (string.IsNullOrEmpty(cuentaClaim))
            {
                Usuario usuario = await _usuarioService.GetUsuarioAsync(User.Identity.Name);
                idCuenta = usuario.IdCuenta;
            }
            else
            {
                //Si hay algo en el claim, parseo
                idCuenta = int.Parse(cuentaClaim);
            }

            return idCuenta;
        }
    }
}

RuteoPedidos.WebAdmin/Views/Tareas/Index.cshtml
@model List<RuteoPedidos.Core.Model.Tareas.Tarea>

@{
    ViewBag.Title = "Listado Tareas";
}


<div class="container-fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-icon card-header-rose">
                        <div class="card-icon">
                            <i class="material-icons">assignment</i>
                        </div>
                        <h4 class="card-title ">Tareas</h4>
                    </div>
                    <br />
                    <div class="card-body">
                        <button class="btn btn-info" id="btnAddTarea">
                            <i class="material-icons">playlist_add</i> Nueva tarea
                        </button>
                        <br />
                        <br />
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th>
                                    Destino
                                </th>
                                <th>
                                    Detalle
                                </th>
                                <th>
                                    Estado
                                </th>
                                <th>
                                    Latitud
                                </th>
                                <th>
                                    Longitud
                                </th>
                                <th>
                                    Motorista
                                </th>
                                </thead>
                                <tbody>
                                    @foreach (var tarea in Model)
                                    {
                                        <tr>
                                            <td>@tarea.DestinoCliente</td>
                                            <td>@tarea.DetalleTarea</td>
                                            <td>@tarea.TextoEstadoTarea</td>
                                            <td>@tarea.LatitudUbicacion</td>
                                            <td>@tarea.LongitudUbicacion</td>
                                            <td>
                                                @if (tarea.Motorista != null)
                                                {
                                                    @Html.Raw(tarea.Motorista.NombreCompleto)
                                                }
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <partial name="_modalAddTarea" model="new CrearTareaVm() "/>
</div>

@section Scripts
{
    <script>
        $(document).ready(function() {

            $(document).on('click', '#btnAddTarea', function(e) {
                $("#myModal").modal('show');
            });

            $(document).on('click', '#btnAgregarTarea', function(e) {
                e.preventDefault();

                Swal.fire('Espere');
                Swal.showLoading();

                //TODO:  Valido si el form esta bien

                //Ahora que el form esta bien, envio la data
                var $formAddTarea = $("#frmAddTarea");
                var url = $formAddTarea.attr('action');
                var method = $formAddTarea.attr('method');
                var data = $formAddTarea.serialize();

                $.ajax({
                    url: url,
                    type: method,
                    data: data,
                    success: function (data) {
                        if (data.exito) {
                            $('#modalLoad').modal('hide');
                            //Como fue exitoso le muestro un swal y recargo la pagina
                            swal({
                                    title: "Exito!",
                                    text: "La tarea fue guardada correctamente",
                                    buttonsStyling: false,
                                    confirmButtonClass: "btn btn-success",
                                    type: "success"
                            })
                                .then(function () {
                                    location.reload();
                                })
                                .catch(swal.noop);

                        }
                    }
                })
            });

        });
    </script>
}

RuteoPedidos.WebAdmin/Views/Tareas/_modalAddTarea.cshtml
@model CrearTareaVm
@{
    Layout = null;

    //Saco la cuenta claim del user
    string cuentaClaim = User.Claims.FirstOrDefault(x => x.Type == "idCuenta")?.Value;
    int idCuenta = string.IsNullOrEmpty(cuentaClaim) ? 0 : int.Parse(cuentaClaim);
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Agregar nueva tarea</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                <i class="material-icons">clear</i>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="card ">
                        <div class="card-header card-header-rose card-header-icon">
                            <div class="card-icon">
                                <i class="material-icons">playlist_add</i>
                            </div>
                        </div>
                        <div class="card-body ">
                            <form asp-controller="Tareas" asp-action="GuardarTarea" method="post" id="frmAddTarea">
                                <div class="form-group">
                                    <label asp-for="DestinoCliente" class="bmd-label-floating">Destino Cliente</label>
                                    <input asp-for="DestinoCliente" type="text" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label asp-for="DetalleTarea" class="bmd-label-floating">Detalle</label>
                                    <textarea asp-for="DetalleTarea" type="text" class="form-control" cols="4" rows="5"></textarea>
                                </div>
                                <div class="form-group">
                                    <label asp-for="LatitudUbicacion" class="bmd-label-floating">Latitud</label>
                                    <input asp-for="LatitudUbicacion" type="number" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label asp-for="LongitudUbicacion" class="bmd-label-floating">Longitud</label>
                                    <input asp-for="LongitudUbicacion" type="number" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label asp-for="IdCuenta" class="bmd-label-floating">Cuenta</label>
                                    <input asp-for="IdCuenta" type="number" class="form-control" value="@idCuenta">
                                </div>
                                <div class="form-group">
                                    <label asp-for="IdMotorista" class="bmd-label-floating">Motorista</label>
                                    <input asp-for="IdMotorista" type="text" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label asp-for="Indicaciones" class="bmd-label-floating">Indicaciones</label>
                                    <input asp-for="Indicaciones" type="text" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label asp-for="TelefonoContacto" class="bmd-label-floating">Telefono</label>
                                    <input asp-for="TelefonoContacto" type="text" class="form-control">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer ">
                            <button type="button" class="btn btn-fill btn-success" id="btnAgregarTarea">Guardar</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>